<a href="https://colab.research.google.com/github/maxbarajas/GramSchmidt/blob/main/GramSch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  #Importamos la biblioteca numpy

def gram_schmidt(A):
    res = A.copy()  # Hacemos una copia de la matriz A
    for i in range(res.shape[1]):  #Iteramos en la matriz a través de dos ciclos for
        for j in range(i):
            # Aplicamos el proceso de Gram Schmidt:
            res[:, i] = res[:, i] - np.dot(res[:, j], res[:, i]) * res[:, j]
        # Normalizamos el resultado 
        res[:, i] = res[:, i] / np.linalg.norm(res[:, i])
    #Regresamos nuestra matriz resultante    
    return res


A = np.array([
    [1, 1, -1],
    [1, -1, 1],
    [-1, 1, 1]
], dtype=float)                 #Declaramos la matriz con los vectores columna a ortonormalizar

print("Matriz A:\n", A)         #Imprimimos la matriz a normalizar 

B = gram_schmidt(A)

print("Matriz Ortonormal: \n", B)

# Verificamos que la norma de cada vector generado en la matriz resultante sea 1

print("Norma de u1:", np.linalg.norm(B[:, 0]))
print("Norma de u2:", np.linalg.norm(B[:, 1]))
print("Norma de u3:", np.linalg.norm(B[:, 2]))

Matriz A:
 [[ 1.  1. -1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]]
Matriz Ortonormal: 
 [[ 5.77350269e-01  8.16496581e-01  2.35513869e-16]
 [ 5.77350269e-01 -4.08248290e-01  7.07106781e-01]
 [-5.77350269e-01  4.08248290e-01  7.07106781e-01]]
Norma de u1: 1.0
Norma de u2: 1.0
Norma de u3: 1.0
